- platform: apcupsd
  resources:
    - linev
    - loadpct
    - bcharge
    - timeleft
    - nompower
- platform: template
  sensors:
    ups_output_power:
      friendly_name: UPS Output Power
      unit_of_measurement: W
      value_template: "{{ states('sensor.ups_load')|float / 100 * states('sensor.ups_nominal_output_power')|float }}"
      icon_template: "mdi:gauge"
      device_class: power