# Travel times to home
- platform: waze_travel_time
  name: waze_twan_to_home
  origin: person.antoine
  destination: zone.home
  region: 'EU'

- platform: waze_travel_time
  name: waze_caro_to_home
  origin: person.caroline
  destination: zone.home
  region: 'EU'

# Travel times to work
- platform: waze_travel_time
  name: waze_twan_to_work
  origin: person.antoine
  destination: zone.twan_work
  region: 'EU'

- platform: waze_travel_time
  name: waze_caro_to_work
  origin: person.caroline
  destination: zone.caro_work
  region: 'EU'