# Alarmm clock based on phone next alarm
- alias: alarmclock
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.date_time_iso') | as_timestamp) == ((state_attr('sensor.app_twanphone_next_alarm', 'Time in Milliseconds') | int / 1000) - 60*15) }}"
  condition:
    - condition: state
      entity_id: person.antoine
      state: 'home'
  action:
    - service: script.alarmclock