- alias: Heating - Ask to turn heating on when coming home
  trigger:
    - platform: state
      entity_id:
        - person.antoine
        - person.caroline
      to: 'not_home'
    - platform: numeric_state
      entity_id: proximity.home
      below: 30
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'not_home'
    - condition: template
      value_template: "{{ state_attr('climate.living_thermostat', 'preset_mode') != 'Schedule' }}"
  action:
    - service_template: >
        {% if trigger.entity_id == "person.antoine" %}
          notify.mobile_app_twan_phone
        {% elif trigger.entity_id == "person.caroline" %}
          notify.mobile_app_iphone_de_caroline
        {% else %}
          notify.phones
        {% endif %}
      data_template:
        title: "Allumer le chauffage ?"
        message: "Déclenché par {{ trigger.to_state.name }}"
        data:
          actions:
            - action: "climate_on"
              title: "Oui"
          push:
            category: climate
            sound:
              name: default
              # critical: 1
              volume: 1.0
          ttl: 0
          priority: high

- alias: Heating - Turn on heating from notification
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'climate_on'
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'climate_on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: all
        preset_mode: Schedule