# Call a service from IFTTT
# JSON data example :
#
# {
#   "action": "call_service",
#   "service": "light.turn_off",
#   "entity_id": "light.bedroom",
#   "data": {
#     "transition": "900"
#   }
# }
#
- alias: IFTTT Call service
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    - service_template: "{{ trigger.event.data.service }}"
      data_template:
        entity_id: "{{ trigger.event.data.entity_id }}"
        data: "{{ trigger.event.data.data }}"