#TODO: Only trigger if light was turned on by motion ?
- alias: Hall lights downstairs - Auto on
  trigger:
    - platform: state
      entity_id: binary_sensor.hall0_modect1_motion
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: numeric_state
        entity_id: sensor.hall0_modect1_illuminance
        below: 4000
  action:
    - service: light.turn_on
      entity_id: light.hall0_ceiling
      data_template:
        profile: >
          {% if states('sensor.time') >= "23:00" or states('sensor.time') <= "01:00" -%}
            evening
          {%- elif states('sensor.time') > "01:00" and states('sensor.time') < "07:00" -%}
            night
          {%- else -%}
            default
          {%- endif %} 
    - delay: 00:02
    - service: light.turn_off
      entity_id: light.hall0_ceiling
      data:
        transition: 30

- alias: Hall lights upstairs - Auto on
  trigger:
    - platform: state
      entity_id: binary_sensor.hall1_modect1_motion
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: numeric_state
        entity_id: sensor.hall1_modect1_illuminance
        below: 4000
  action:
    - service: light.turn_on
      entity_id: light.hall1_ceiling
      data_template:
        profile: >
          {% if states('sensor.time') >= "23:00" or states('sensor.time') <= "01:00" -%}
            evening
          {%- elif states('sensor.time') > "01:00" and states('sensor.time') < "07:00" -%}
            night
          {%- else -%}
            default
          {%- endif %} 
    - delay: 00:02
    - service: light.turn_off
      entity_id: light.hall1_ceiling
      data:
        transition: 30