- alias: living_radio_auto_off
  trigger:
    - platform: state
      entity_id: media_player.living_mibox
      to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.living_cca_radio
      state: 'playing'
  action:
    - service: media_player.turn_off
      entity_id: media_player.living_cca_radio