# Hue Dimmer Switch salon (00:17:88:01:02:d5:b7:f2)

- alias: Switch lights on in Salon
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d5:b7:f2"
      command: "on"
  action:
  - service: light.turn_on
    entity_id: light.living

- alias: Switch lights off in Salon
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d5:b7:f2"
      command: "off_with_effect"
  action:
  - service: light.turn_off
    entity_id: light.living

- alias: Increase brightness in Salon
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d5:b7:f2"
      command: "step"
      args: [0, 30, 9]
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d5:b7:f2"
      command: "step"
      args: [0, 56, 9]
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.living
      brightness: >
          {% if state_attr('light.living' , 'brightness') < 230 %}
            {{ state_attr('light.living' , 'brightness') + 25 }}
          {% else %} 255 {% endif %}

- alias: Decrease brightness in Salon
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d5:b7:f2"
      command: "step"
      args: [1, 30, 9]
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d5:b7:f2"
      command: "step"
      args: [1, 56, 9]
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.salon
      brightness: >
          {% if state_attr('light.living' , 'brightness') > 25 %}
            {{ state_attr('light.living' , 'brightness') - 25 }}
          {% else %} 1 {% endif %}