- alias: "UPS - Alert if loss of power"
  trigger:
    platform: state
    entity_id: binary_sensor.ups_online_status
    to: 'off'
  action:
    - service: notify.all
      data_template:
        title: Panne de courant
        message: "Il reste {{ states('sensor.ups_time_left') | string }}minutes de batterie."
        data:
          ttl: 0
          priority: high

- alias: "UPS - Alert low battery"
  trigger:
    platform: numeric_state
    entity_id: sensor.ups_time_left
    below: 5
  action:
    - service: notify.all
      data_template:
        title: Batterie faible
        message: "Il reste moins de {{ states('sensor.ups_time_left') | string }}minutes de batterie."
        data:
          ttl: 0
          priority: high